#!/usr/bin/env bash

# shellcheck disable=SC1090

# Set strict bash mode
set -euo pipefail

# Default varable values
TOOLBOX_LOG_LEVEL=${TOOLBOX_LOG_LEVEL:-INFO}
export TOOLBOX_DOCKER_SKIP=${TOOLBOX_DOCKER_SKIP:-false}

# Trace with "-x" mode
if [ "${TOOLBOX_LOG_LEVEL}" == "TRACE" ]; then
  set -x
fi

# Includes
# https://stackoverflow.com/a/12694189
SCRIPT_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$SCRIPT_DIR" ]]; then SCRIPT_DIR="$PWD"; fi
. "$SCRIPT_DIR/../toolwrap/includes/util.sh"
. "$SCRIPT_DIR/../toolwrap/includes/docker.sh"
. "$SCRIPT_DIR/includes/variant.sh"

export TOOL_PATH=${TOOL_PATH:-$(find_tool_path "${1}")}

# Decide about Docker mode
if [ "${TOOLBOX_RUN}" == "false" ] && [ "${TOOLBOX_DOCKER_SKIP}" == "false" ]; then
  if [ -f /.dockerenv ]; then
    echo "Inside docker already, setting TOOLBOX_DOCKER_SKIP to true"
    TOOLBOX_DOCKER_SKIP=true
  fi
fi

if [ "${TOOLBOX_DOCKER_SKIP}" == "true" ]; then
  _log DEBUG "Skip the processing of variant variables"
else
  _prepare_variant_env_vars "$@"
fi

_exec_tool "${@}"
