config:
  toolbox-variant:
    params:
      template: toolbox/deps/toolbox-variant/templates/run.tpl
      image: aroq/toolbox-variant:0.1.45
      tool_dirs:
      - toolbox/deps/toolbox-docker
      - toolbox/deps/toolbox-wrap
      - toolbox/deps/toolbox-variant
