config:
  toolbox-variant:
    params:
      template: toolbox/deps/toolbox-variant/templates/run.tpl
      image: aroq/toolbox-variant:0.1.15
      env:
        VARIANT_HIDE_EXTRA_CMDS: true
        VARIANT_LOG_LEVEL: warning
